<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8c013662-776e-4ef1-80b7-d1537edb7b3a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventApp.Infrastructure\EventApp.Infrastructure.csproj" />
    <ProjectReference Include="..\EventApp.Application\EventApp.Application.csproj" />
  </ItemGroup>

</Project>
